### PR TITLE
Fixing optional argument exception reporting missing an offset for array lookup

### PR DESCRIPTION
**Pull request by lucyainsworth**

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
This looks good! Could you add a quick test for this case?

**Comment by lucyainsworth** [comment]
Done! Do i need to make a separate pull request for the test?  First time submitting a fix on github so i want to make i do things properly :)

**Comment by AlexGhiondea** [comment]
This is great! Having the code and test in the same PR is the preferred way IMO! :)

Thank you!! I will merge and release the updated package later today!!!

**Comment by lucyainsworth** [comment]
Sounds good, thanks Alex!

**Pull request merged**
